<?php

namespace MiroBundle\Repository;

/**
 * blahRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class blahRepository extends \Doctrine\ORM\EntityRepository
{
}
