<?php

namespace TwoESystems\AirlinesBundle\Repository;

use Symfony\Component\Validator\Constraints\Count;
use TwoESystems\AirlinesBundle\Entity\Country;

/**
 * AirlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirlineRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllByNameAndCountry(string $name, Country $country)
    {
        return $this->findBy(['title' => $name, 'country' => $country]);
    }

    public function getAllByCountry(Country $country, int $limit): array
    {
        return $this->findBy(['country' => $country], ['title' => 'DESC'], $limit);
    }
}
