<?php

namespace TwoESystems\AirlinesBundle\Repository;

/**
 * AirlineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirlineRepository extends \Doctrine\ORM\EntityRepository
{
}
