aviation_country:
    resource: "@AviationCountryBundle/Controller/"
    type:     annotation
    prefix:   /

aviation_airlines:
    resource: "@AviationAirlinesBundle/Controller/"
    type:     annotation
    prefix:   /

miro:
    resource: "@MiroBundle/Controller/"
    type:     annotation
    prefix:   /miro

app:
    resource: '@AppBundle/Controller/'
    type: annotation
