services:
  aviation.repository.airlines:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Aviation\AirlinesBundle\Entity\Airline
  country.repository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
        - Aviation\CountryBundle\Entity\Country
  aviation.repository.flights:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Aviation\AirlinesBundle\Entity\Flight
  aviation.repository.airports:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
        - Aviation\AirlinesBundle\Entity\Airport
  sexyairlines:
      class: Aviation\AirlinesBundle\Service\SexyAirlines
      arguments:
        - "@aviation.repository.airlines"
        - "10"
  aviation.airlines.service.sexy_airlines.top5:
      class: Aviation\AirlinesBundle\Service\SexyAirlines
      arguments:
        - "@country.repository"
        - "@aviation.repository.airlines"
        - "%sexyairlinescount%"
  aviation.airlines.service.flight_search:
      class: Aviation\AirlinesBundle\Service\FlightSearch
      arguments:
        - "@aviation.repository.airports"
        - "@aviation.repository.flights"

