services:
  aviation.repository.airlines:
    class: Doctrine\ORM\EntityRepository
    factory: ['@doctrine.orm.default_entity_manager', getRepository]
    arguments:
      - Aviation\AirlinesBundle\Entity\Airline
  country.repository:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
        - Aviation\AirlinesBundle\Entity\Country
  sexyairlines:
      class: Aviation\AirlinesBundle\Service\SexyAirlines
      arguments:
        - "@country.repository"
        - "@aviation.repository.airlines"
        - "2"
  aviation.airlines.service.sexy_airlines.top5:
      class: Aviation\AirlinesBundle\Service\SexyAirlines
      arguments:
        - "@country.repository"
        - "@aviation.repository.airlines"
        - "%sexyairlinescount%"
