#Aviation\AirlinesBundle\Entity\Airline:
#  properties:
#    tomo:
#      - NotBlank:
#          message: 'this was a hidden field, not meant to be left blank'
#  getters:
#    legal:
#      - 'IsTrue' : {message: 'not legal'}