<?php

namespace Aviation\AirlinesBundle\Repository;

use Aviation\CountryBundle\Entity\Country;

/**
 * AirlineRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AirlineRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param string                                 $name
     * @param \Aviation\CountryBundle\Entity\Country $country
     *
     * @return array
     */
    public function getAllByNameAndCountry(string $name, Country $country): array
    {
        return $this->findBy(['title' => $name, 'country' => $country]);
    }

    /**
     * @param \Aviation\CountryBundle\Entity\Country $country
     * @param int                                    $limit
     *
     * @return array
     */
    public function getAllByCountry(Country $country, int $limit): array
    {
        return $this->findBy(['country' => $country], ['title' => 'DESC'], $limit);
    }
}
